services:
  db:
    image: mysql:9.1
    container_name: my_mysql
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=qrplansdb
    volumes:
      - my_custom_volume:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:5.2.1
    container_name: my_phpmyadmin
    depends_on:
      - db
    ports:
      - '8080:80'
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=${PMA_PASSWORD}
volumes:
  my_custom_volume:
    name: volume_persisted_data_qrplans
